# Generated by Django 4.2.2 on 2024-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stadiums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("city", models.CharField(max_length=20)),
                ("counrty", models.CharField(max_length=20)),
                ("desc", models.TextField()),
                ("cost", models.IntegerField()),
                ("picture", models.CharField(max_length=300)),
            ],
        ),
    ]
