# Generated by Django 4.2.2 on 2024-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadiums",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
