# Generated by Django 4.2.2 on 2024-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_stadiums_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadiums",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
