# Generated by Django 4.2.2 on 2024-02-24 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_stadiums_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stadiums",
            old_name="counrty",
            new_name="country",
        ),
    ]
