# Generated by Django 4.2.2 on 2024-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_stadiums_map_alter_stadiums_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=1)),
                ("phone", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=30)),
            ],
        ),
    ]
