# Generated by Django 4.2.2 on 2024-02-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='stadiums',
            name='hotels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.hotel'),
            preserve_default=False,
        ),
    ]
