# Generated by Django 4.2.2 on 2024-02-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotel_stadiums_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiums',
            name='hotels',
        ),
        migrations.AddField(
            model_name='hotel',
            name='stad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.stadiums'),
            preserve_default=False,
        ),
    ]
