# Generated by Django 5.0.2 on 2024-02-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_stadiums_hotels_hotel_stad"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadiums",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="stadiums",
            name="longtitude",
            field=models.FloatField(null=True),
        ),
    ]
