# Generated by Django 5.0.2 on 2024-02-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_stadiums_latitude_stadiums_longtitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="description",
            new_name="properties",
        ),
        migrations.RenameField(
            model_name="stadiums",
            old_name="longtitude",
            new_name="longitude",
        ),
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="map",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="review",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="max_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="min_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="stadiums",
            name="picture",
            field=models.JSONField(),
        ),
    ]
